# This is a template for setting up a blog page using mkdocs-bloggin-plugin
# (https://github.com/liang2kl/mkdocs-blogging-plugin). Please follow the
# guide (https://liang2kl.github.io/mkdocs-blogging-plugin) for further
# customization. You can also follow an example project
# (https://liang2kl.github.io/mkdocs-blogging-plugin-example) to customize
# the appearance using templates.

site_name: Zyrah Bernardino
site_url: "https://zyrahbernardino.com"
repo_url: https://github.com/zyrahb/website
repo_name: zyrahb/website
edit_uri: ""

use_directory_urls: false

theme:
  name: 'terminal'

plugins:
  - blogging:
      dirs:
        - projects
